name: Translate projects

on:
  push:
    paths:
      - 'projects.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run translation script
      run: python translate.py

    - name: Commit translated file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add projects_en.json
        git commit -m "Update projects_en.json with new translations" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}